// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0JMDhu2Nts3W5rPpZ95DI2HMjeoy4vHc',
    appId: '1:1083454830976:web:00501a1f91fdad48896965',
    messagingSenderId: '1083454830976',
    projectId: 'hyukflix',
    authDomain: 'hyukflix-ce113.firebaseapp.com',
    storageBucket: 'hyukflix.appspot.com',
    measurementId: 'G-2DLFV85SNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_nD7YtsZG6HhKSVm7M4riCxCIVUb3PKE',
    appId: '1:1083454830976:android:09b6df8b4dc66fff896965',
    messagingSenderId: '1083454830976',
    projectId: 'hyukflix',
    storageBucket: 'hyukflix.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZIOUz6h07Q63W7XV-ad37zzFy0c9Mawg',
    appId: '1:1083454830976:ios:a25f8eb536071ef1896965',
    messagingSenderId: '1083454830976',
    projectId: 'hyukflix',
    storageBucket: 'hyukflix.appspot.com',
    iosClientId: '1083454830976-glogu4l0ing8f2ej7pfboj9om6bkj2jc.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflixCloneTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZIOUz6h07Q63W7XV-ad37zzFy0c9Mawg',
    appId: '1:1083454830976:ios:892db1d373f2b409896965',
    messagingSenderId: '1083454830976',
    projectId: 'hyukflix',
    storageBucket: 'hyukflix.appspot.com',
    iosClientId: '1083454830976-7tbll9ohpn2s9er2dlkrjru38imqha09.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflixCloneTest.RunnerTests',
  );
}
